export const DEFAULT_GENRES = [
  'Lofi',
  'All',
  'Chillout',
  'Relax',
  'Study',
  'Focus',
  'Sleep',
  'Lounge',
  'Downtempo',
  'Jazz',
  'Ambient',
  'Classical',
  'Piano',
  'Guitar',
  'Synthwave',
  'Vaporwave',
  'Electronic',
  'House',
  'Deep House',
  'Techno',
  'Trance',
  'Drum and Bass',
  'Hip Hop',
  'Pop',
  'Rock',
  'Indie',
  'Metal',
  'Reggae',
  'Blues',
  'Soul',
  'Funk',
  'Disco',
  'R&B',
  'Country',
  'Latin',
  'Afrobeats'
] as const

export const SHARE_FALLBACK_URL =
  'https://drive.google.com/drive/folders/1ZqQDKF2eMO4BWcjzXMOr6aE7GHLoM4BY?usp=sharing'
